function Apropos(action,varargin)

%%================================================================
%%
%/*** la figure secondaire
AproposFig=figure('Name','A propos', ...
   'NumberTitle','off',...
   'tag', 'A propos', ...
   'BusyAction','Queue','Interruptible','off', ...
   'Color', [123 152 225]/256,...
   'position',[400 300 300 220],...
   'IntegerHandle', 'off', ...
   'WindowStyle','modal',...
   'Colormap', gray(256));

Std.Interruptible = 'off';
Std.BusyAction = 'queue';
Ctl = Std;
Ctl.Units = 'Pixels';
Ctl.Parent = AproposFig;

texte=Ctl;
texte.Interruptible='off';
texte.Style='text';
texte.Horiz='left';
texte.Background=[123 152 225]/256;
texte.Foreground='white';
texte.FontWeight='bold';
texte.Fontsize=12;

% %%/******* text label A Propos **************/
chaine1='Ce projet a été réalisé par :';
hs.hTexteApropos=uicontrol(texte,...
   'Position',[20 110 220 100], ...
   'String',chaine1);

chaine2='Rachid El Alami';
hs.hTexteApropos=uicontrol(texte,...
   'Position',[30 80 180 100], ...
   'String',chaine2);

chaine3='El Hassane Khabbiza';
hs.hTexteApropos=uicontrol(texte,...
   'Position',[30 60 180 100], ...
   'String',chaine3);

chaine4='Hicham Zaaroui';
hs.hTexteApropos=uicontrol(texte,...
   'Position',[30 40 180 100], ...
   'String',chaine4);

chaine5='Encadré Par :     Hamid Tahiri';
hs.hTexteApropos=uicontrol(texte,...
   'Position',[150 10 110 100], ...
   'String',chaine5);

chaine6='Master SIS  - LESSI -   2007/2008';
hs.hTexteApropos=uicontrol(texte,...
   'Foreground','red',...
   'Position',[30 -40 260 100], ...
   'String',chaine6);

%==============================================================
%/*** le bouton ok
h.hBtnOk=uicontrol( ...
   'Parent',AproposFig, ...
   'BusyAction','Queue','Interruptible','off',...
   'Style','pushbutton', ...
   'Units','pixels', ...
   'Position',[100 10 100 25], ...
   'String','Ok', ...
   'Callback','close(gcf)');

% %============================================================
% %/*** les axes de l'image de fond
% h.hAxImgFond=axes('Parent',AproposFig,...
%    'units', 'pixels', ...
%    'BusyAction','Queue','Interruptible','off',...
%    'ydir', 'reverse', ...
%    'XLim', [.5 128.5], ...
%    'YLim', [.5 128.5],...
%    'CLim', [0 1], ...
%    'XTick',[],'YTick',[], ...
%    'Position', [0 0 303 255]);
% 
% %==============================================================
% %/*** initialiser les axes de l'images de fond
% h.hImgFond = image('Parent', h.hAxImgFond,...
%    'CData',[], ...
%    'BusyAction','Queue','Interruptible','off',...
%    'CDataMapping', 'scaled', ...
%    'Xdata', [1 128],...
%    'Ydata', [1 128],...
%    'EraseMode', 'normal');
% 
% imf=imread('vista.jpg');
% imf=double(imf)/255;
% set(h.hImgFond, 'Cdata', imf);